sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull karthequian/gruyere:latest
- docker login -u=jstrad -p=1221J@son1107
- docker pull jstrad/sectools:alpha
- docker run --rm -d -p 8008:8008 karthequian/gruyere:latest
- docker run --name sectools --rm -td -v ~/secfiles:/gauntlt/bin jstrad/sectools:alpha /bin/bash 
- docker ps -a
- ./scripts/travis-config.sh

script:
 - cat ./config/cucumber.yml
 - docker exec -d -w/gauntlt/bin -ti sectools nmap -p 8008 172.17.0.1
 - docker exec -d -w/gauntlt/bin -ti sectools ./gauntlt /gauntlt/attacks/nmap.attack
